version: "3"
services:
  client:
    image: singhaditya3116/multi-client
    hostname: client
    restart: always
    mem_limit: 128m

  api:
    image: singhaditya3116/multi-server
    hostname: api
    restart: always
    mem_limit: 128m
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}

  worker:
    image: singhaditya3116/multi-worker
    hostname: worker
    restart: always
    mem_limit: 128m
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  nginx:
    image: singhaditya3116/multi-nginx
    hostname: nginx
    restart: always
    mem_limit: 128m
    depends_on:
      - client
      - api
    ports:
      - "80:80"